In [35]:
import numpy as np

In [36]:
A = np.array([[2, 7],[1, 9],[0, -7]])

In [37]:
B = np.array([[7,-1, 0],[1,2, -3]])

## Multiplication of two matrices

In [38]:
result = np.dot(A, B)

## Addition and subtraction of two matrices

In [39]:
A = np.array([[1, 25, 3, 4],
              [2, 6, 7, 8],
              [9, 16, 13, 12]])

In [40]:
B = np.array([[12, 21, 10, 9],
              [81, 87, 6, 5],
              [4, 3, 6, 1]])

In [41]:
sum_result = A + B

In [42]:
diff_result = A - B

In [43]:
print(sum_result)

[[13 46 13 13]
 [83 93 13 13]
 [13 19 19 13]]


In [44]:
print(diff_result)

[[-11   4  -7  -5]
 [-79 -81   1   3]
 [  5  13   7  11]]
